"""WP-141 — `fettle init`: one-command setup replacing the symlink ritual.

Idempotent. Detects installed agents and wires everything Fettle needs:

1. Repo scaffolding    — .fettle.toml, .fettle-ignore (skipped if present)
2. Claude Code         — ~/.claude/plugins/fettle symlink to the checkout
3. OpenCode            — plugin registration in ~/.config/opencode/config.json
4. Commit-time guards  — .pre-commit-config.yaml + `pre-commit install`
5. --install-tools     — pinned ruff/semgrep/pre-commit via uv (never inside
                         hooks; that was audit finding D6)

Every step reports ok / created / skipped / manual-action-needed. Exit 0
unless a requested action failed.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root (clone mode)
from fettle.install import DEFAULT_FETTLE_TOML, DEFAULT_IGNORE  # noqa: E402

# Pinned tool versions for --install-tools (kept in lockstep with ci.yml).
PINNED_TOOLS = {
    "ruff": "0.15.20",
    "semgrep": "1.168.0",
    "pre-commit": "4.4.0",
}

PRE_COMMIT_CONFIG = """\
# Fettle commit-time verification — generated by `fettle init`.
# The same policy your editor hooks and CI enforce, before a commit exists.
repos:
  - repo: https://github.com/MilindGaharwar/fettle
    rev: v1.2.0   # pin a tag; bump deliberately
    hooks:
      - id: fettle-check
      - id: fettle-rules-validate
"""


def _plugin_root() -> Path:
    """The Fettle checkout root (parent of the fettle/ package)."""
    return Path(__file__).resolve().parent.parent


def _is_clone_mode() -> bool:
    """Hooks require a git checkout — wheels don't ship run.sh / hooks.json."""
    root = _plugin_root()
    return (root / "hooks" / "hooks.json").is_file() and (root / "fettle" / "run.sh").is_file()


class Step:
    def __init__(self, name: str, status: str, detail: str = "") -> None:
        self.name = name
        self.status = status  # ok | created | skipped | action | error
        self.detail = detail

    def to_dict(self) -> dict:
        return {"name": self.name, "status": self.status, "detail": self.detail}


def init_repo_files(repo_root: Path, dry_run: bool) -> list[Step]:
    steps = []
    for fname, content in ((".fettle.toml", DEFAULT_FETTLE_TOML), (".fettle-ignore", DEFAULT_IGNORE)):
        target = repo_root / fname
        if target.exists():
            steps.append(Step(fname, "ok", "already present"))
        elif dry_run:
            steps.append(Step(fname, "created", "(dry-run) would create"))
        else:
            target.write_text(content)
            steps.append(Step(fname, "created", str(target)))
    return steps


def init_claude_code(dry_run: bool) -> list[Step]:
    claude_dir = Path.home() / ".claude"
    if not claude_dir.is_dir():
        return [Step("claude-code", "skipped", "~/.claude not found — Claude Code not installed")]
    if not _is_clone_mode():
        return [Step("claude-code", "action",
                     "hooks need a git checkout (wheels don't ship run.sh) — "
                     "git clone https://github.com/MilindGaharwar/fettle ~/projects/fettle && fettle init")]

    link = claude_dir / "plugins" / "fettle"
    root = _plugin_root()
    if link.is_symlink() or link.exists():
        try:
            if link.resolve() == root.resolve():
                return [Step("claude-code", "ok", f"plugin already linked: {link} -> {root}")]
        except OSError:
            pass
        return [Step("claude-code", "action",
                     f"{link} exists but does not point to {root} — resolve manually")]
    if dry_run:
        return [Step("claude-code", "created", f"(dry-run) would symlink {link} -> {root}")]
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(root)
    return [Step("claude-code", "created", f"symlinked {link} -> {root}")]


def init_opencode(dry_run: bool) -> list[Step]:
    config_dir = Path.home() / ".config" / "opencode"
    if not config_dir.is_dir():
        return [Step("opencode", "skipped", "~/.config/opencode not found — OpenCode not installed")]
    if not _is_clone_mode():
        return [Step("opencode", "action", "plugin requires a git checkout — see docs/OPENCODE.md")]

    plugin_uri = f"file://{_plugin_root()}/integrations/opencode/fettle.ts"
    config_path = config_dir / "config.json"
    try:
        config = json.loads(config_path.read_text()) if config_path.is_file() else {}
        if not isinstance(config, dict):
            raise ValueError("config.json is not an object")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [Step("opencode", "action",
                     f"could not parse {config_path} ({exc}) — add plugin entry manually: {plugin_uri}")]

    plugins = config.get("plugin")
    if not isinstance(plugins, list):
        plugins = []
    if plugin_uri in plugins:
        return [Step("opencode", "ok", "plugin already registered")]
    if dry_run:
        return [Step("opencode", "created", f"(dry-run) would register {plugin_uri}")]
    plugins.append(plugin_uri)
    config["plugin"] = plugins
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    return [Step("opencode", "created", f"registered plugin in {config_path} — restart OpenCode")]


def init_pre_commit(repo_root: Path, dry_run: bool) -> list[Step]:
    steps = []
    config_path = repo_root / ".pre-commit-config.yaml"
    if config_path.exists():
        steps.append(Step("pre-commit-config", "ok", "already present"))
    elif dry_run:
        steps.append(Step("pre-commit-config", "created", "(dry-run) would create"))
    else:
        config_path.write_text(PRE_COMMIT_CONFIG)
        steps.append(Step("pre-commit-config", "created", str(config_path)))

    hook_installed = _pre_commit_hook_installed(repo_root)
    if hook_installed:
        steps.append(Step("pre-commit-install", "ok", "commit-time guards wired"))
        return steps

    binary = shutil.which("pre-commit")
    if not binary:
        local = os.path.expanduser("~/.local/bin/pre-commit")
        binary = local if os.path.isfile(local) and os.access(local, os.X_OK) else None
    if not binary:
        steps.append(Step("pre-commit-install", "action",
                          "pre-commit not installed — run: fettle init --install-tools"))
        return steps
    if dry_run:
        steps.append(Step("pre-commit-install", "created", "(dry-run) would run pre-commit install"))
        return steps
    try:
        result = subprocess.run(
            [binary, "install"], cwd=str(repo_root),
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            steps.append(Step("pre-commit-install", "created", "commit-time guards wired"))
        else:
            steps.append(Step("pre-commit-install", "error",
                              (result.stderr or result.stdout).strip()[:200]))
    except (OSError, subprocess.TimeoutExpired) as exc:
        steps.append(Step("pre-commit-install", "error", str(exc)))
    return steps


def _pre_commit_hook_installed(repo_root: Path) -> bool:
    hook = repo_root / ".git" / "hooks" / "pre-commit"
    try:
        return hook.is_file() and "pre-commit" in hook.read_text()
    except OSError:
        return False


def install_tools(dry_run: bool) -> list[Step]:
    """Pinned tool installs via uv — explicit user action, never hook-time (D6)."""
    uv = shutil.which("uv")
    if not uv:
        return [Step("install-tools", "action",
                     "uv not found — install it first: https://docs.astral.sh/uv/")]
    steps = []
    for tool, version in PINNED_TOOLS.items():
        existing = shutil.which(tool) or (
            os.path.expanduser(f"~/.local/bin/{tool}")
            if os.path.isfile(os.path.expanduser(f"~/.local/bin/{tool}")) else None
        )
        if existing:
            steps.append(Step(f"tool:{tool}", "ok", existing))
            continue
        if dry_run:
            steps.append(Step(f"tool:{tool}", "created", f"(dry-run) would install {tool}=={version}"))
            continue
        result = subprocess.run(
            [uv, "tool", "install", f"{tool}=={version}"],
            capture_output=True, text=True, timeout=600,
        )
        if result.returncode == 0:
            steps.append(Step(f"tool:{tool}", "created", f"{tool}=={version}"))
        else:
            steps.append(Step(f"tool:{tool}", "error", (result.stderr or "").strip()[:200]))
    return steps


def run_init(repo_root: Path, *, tools: bool = False, dry_run: bool = False) -> tuple[list[Step], int]:
    steps: list[Step] = []
    steps += init_repo_files(repo_root, dry_run)
    steps += init_claude_code(dry_run)
    steps += init_opencode(dry_run)
    steps += init_pre_commit(repo_root, dry_run)
    if tools:
        steps += install_tools(dry_run)
    exit_code = 1 if any(s.status == "error" for s in steps) else 0
    return steps, exit_code


_MARKS = {"ok": "ok ", "created": "new", "skipped": "-- ", "action": "!! ", "error": "ERR"}


def print_steps(steps: list[Step]) -> None:
    print("── fettle init ──\n")
    for s in steps:
        print(f"[{_MARKS.get(s.status, '?')}] {s.name:<20} {s.detail}")
    actions = [s for s in steps if s.status == "action"]
    if actions:
        print(f"\n{len(actions)} step(s) need your attention (marked !!).")
    else:
        print("\n✓ Fettle is wired. `fettle doctor` verifies the environment.")
