"""`fettle init --interactive` / `--profile` — v1.6 slice B.

Detect first, ask second (design doc 14, D-B1/D-B2): the stack is
detected from repo markers; the interview only asks what is undetectable
(team shape, enforcement appetite, compliance sensitivity, multi-agent
plans). The result is an *annotated* .fettle.toml — every choice carries
a comment explaining why — validated against the config schema by test.

Profiles are the same answers as data, for non-TTY use:
  solo        — one human, advisory-first
  team        — shared repo, plans + worklogs on
  enterprise  — strict modes, audit trail, multi-agent governance
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

#: Profile -> interview answers (D-B2: presets are data, schema-tested).
PROFILES: dict[str, dict[str, bool]] = {
    "solo": {"team": False, "strict": False, "compliance": False, "multi_agent": False},
    "team": {"team": True, "strict": False, "compliance": False, "multi_agent": False},
    "enterprise": {"team": True, "strict": True, "compliance": True, "multi_agent": True},
}

_LANG_MARKERS = {
    "python": ("pyproject.toml", "setup.py", "requirements.txt"),
    "typescript/javascript": ("package.json", "tsconfig.json"),
    "go": ("go.mod",),
    "rust": ("Cargo.toml",),
}


def detect_stack(repo_root: Path) -> dict[str, Any]:
    """Cheap, deterministic repo-marker detection (no tree walk)."""
    languages = [
        lang for lang, markers in _LANG_MARKERS.items()
        if any((repo_root / m).is_file() for m in markers)
    ]
    ci = ""
    if (repo_root / ".github" / "workflows").is_dir():
        ci = "github"
    elif (repo_root / ".gitlab-ci.yml").is_file():
        ci = "gitlab"
    return {"languages": languages, "ci": ci}


def _ask_bool(ask: Callable[[str], str], prompt: str, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    answer = ask(prompt + suffix).strip().lower()
    if not answer:
        return default
    return answer.startswith("y")


def run_interview(
    repo_root: Path,
    ask: Callable[[str], str] = input,
    say: Callable[[str], None] = print,
) -> dict[str, Any]:
    """Five questions, each mapped to config. `ask` injectable for tests."""
    detected = detect_stack(repo_root)
    say("── fettle init: five questions to fit the config to this project ──")
    answers: dict[str, Any] = dict(PROFILES["solo"])
    answers["team"] = _ask_bool(
        ask, "1/5 Will multiple people (or agents) work in this repo?", False)
    answers["strict"] = _ask_bool(
        ask, "2/5 Start strict (block on violations)? Advisory-first is "
             "recommended — promote with `fettle ratchet` once trusted.", False)
    answers["compliance"] = _ask_bool(
        ask, "3/5 Compliance/secrets sensitivity (audit trail, MCP trust)?", False)
    answers["multi_agent"] = _ask_bool(
        ask, "4/5 Multi-agent workflows planned (spawned/delegated agents)?", False)
    stack = ", ".join(detected["languages"]) or "none detected"
    ci = detected["ci"] or "none"
    answers["stack_confirmed"] = _ask_bool(
        ask, f"5/5 Detected stack: {stack}; CI: {ci}. Correct?", True)
    return answers


def render_config(answers: dict[str, Any], detected: dict[str, Any]) -> str:
    """Annotated .fettle.toml from answers + detection."""
    team = bool(answers.get("team"))
    strict = bool(answers.get("strict"))
    compliance = bool(answers.get("compliance"))
    multi_agent = bool(answers.get("multi_agent"))
    mode = "enforce" if strict else "advisory"

    lines: list[str] = [
        "# Fettle configuration — generated by `fettle init` from your answers.",
        "# Reference: https://github.com/MilindGaharwar/fettle/blob/main/docs/CONFIG.md",
        f"# Shape: {'team' if team else 'solo'}"
        f"{', strict' if strict else ', advisory-first'}"
        f"{', compliance' if compliance else ''}"
        f"{', multi-agent' if multi_agent else ''}",
    ]
    if not answers.get("stack_confirmed", True):
        lines.append("# NOTE: you flagged the detected stack as wrong — review [paths] and gates.")
    if detected.get("languages"):
        lines.append(f"# Detected: {', '.join(detected['languages'])}"
                     + (f"; CI: {detected['ci']}" if detected.get("ci") else ""))
    lines += [
        "",
        "[gates.lint]           # per-edit lint (ruff + semgrep)",
        "enabled = true",
        f'mode = "{mode}"' + ("" if strict else '       # promote to "enforce" via fettle ratchet'),
        "",
        "[gates.destructive]    # rm -rf, force-push, reset --hard guards",
        "enabled = true",
        f'mode = "{mode}"',
        "",
        "[gates.commit_message] # conventional commits",
        "enabled = true",
        f'mode = "{mode}"',
    ]
    plans_on = team or multi_agent
    lines += [
        "",
        "[gates.plan]           # multi-file work requires a plan"
        + ("" if plans_on else " — enable when work gets bigger"),
        f"enabled = {'true' if plans_on else 'false'}",
        "session_plans = true   # fettle plan start|check (.fettle/plans/)",
        "",
        "[gates.worklog]        # Stop requires a worklog entry"
        + ("" if plans_on else " — enable alongside plans"),
        f"enabled = {'true' if plans_on else 'false'}",
        'mode = "advisory"',
        f'scope = "{"session" if plans_on else "daily"}"',
    ]
    if compliance:
        lines += [
            "",
            "[gates.bash_audit]     # compliance: audit every shell command",
            "enabled = true",
            "",
            "[gates.mcp_trust]      # compliance: only allowlisted MCP servers",
            "enabled = true",
        ]
    if multi_agent:
        lines += [
            "",
            "[gates.agent_spawn]    # nested agent launches must use fettle spawn",
            "enabled = true",
            f'mode = "{mode}"',
            "",
            "[gates.claims]         # claim-before-work in agent worktrees",
            "enabled = true",
            'mode = "advisory"',
            "",
            "[worktrees]            # agents work in isolated worktrees",
            f"require = {'true' if strict else 'false'}"
            + ("" if strict else "        # true once the team works worktree-first"),
        ]
    return "\n".join(lines) + "\n"


def write_config(repo_root: Path, content: str, force: bool = False) -> tuple[bool, str]:
    """D-B1: never overwrite an existing .fettle.toml without --force."""
    target = repo_root / ".fettle.toml"
    if target.exists() and not force:
        return False, f"{target} already exists — use --force to overwrite"
    target.write_text(content, encoding="utf-8")
    return True, str(target)
