"""WP-141 — `fettle init`: one-command setup replacing the symlink ritual.

Idempotent. Detects installed agents and wires everything Fettle needs:

1. Repo scaffolding    — .fettle.toml, .fettle-ignore (skipped if present)
2. Claude Code         — ~/.claude/plugins/fettle symlink to the checkout
3. OpenCode            — plugin registration in ~/.config/opencode/config.json
4. Codex CLI           — hook registration in ~/.codex/hooks.json
5. Gemini CLI          — hook registration in ~/.gemini/settings.json
6. Commit-time guards  — .pre-commit-config.yaml + `pre-commit install`
7. --install-tools     — pinned ruff/semgrep/pre-commit via uv (never inside
                         hooks; that was audit finding D6)

Every step reports ok / created / skipped / manual-action-needed. Exit 0
unless a requested action failed.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import shlex
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root (clone mode)
from fettle.install import DEFAULT_FETTLE_TOML, DEFAULT_IGNORE  # noqa: E402
from fettle.supply_chain import (  # noqa: E402,F401 — canonical home (WP-147)
    PINNED_TOOLS,
    SYSTEM_TOOLS,
    system_install_argv,
    system_install_hint,
)

PRE_COMMIT_CONFIG = """\
# Fettle commit-time verification — generated by `fettle init`.
# The same policy your editor hooks and CI enforce, before a commit exists.
repos:
  - repo: https://github.com/MilindGaharwar/fettle
    rev: v1.3.0   # pin a tag; bump deliberately
    hooks:
      - id: fettle-check
      - id: fettle-rules-validate
"""


def _plugin_root() -> Path:
    """The Fettle checkout root (parent of the fettle/ package)."""
    return Path(__file__).resolve().parent.parent


def _is_clone_mode() -> bool:
    """Hooks require a git checkout — wheels don't ship run.sh / hooks.json."""
    root = _plugin_root()
    return (root / "hooks" / "hooks.json").is_file() and (root / "fettle" / "run.sh").is_file()


class Step:
    def __init__(self, name: str, status: str, detail: str = "") -> None:
        self.name = name
        self.status = status  # ok | created | skipped | action | error
        self.detail = detail

    def to_dict(self) -> dict:
        return {"name": self.name, "status": self.status, "detail": self.detail}


def init_repo_files(repo_root: Path, dry_run: bool) -> list[Step]:
    steps = []
    for fname, content in ((".fettle.toml", DEFAULT_FETTLE_TOML), (".fettle-ignore", DEFAULT_IGNORE)):
        target = repo_root / fname
        if target.exists():
            steps.append(Step(fname, "ok", "already present"))
        elif dry_run:
            steps.append(Step(fname, "created", "(dry-run) would create"))
        else:
            target.write_text(content)
            steps.append(Step(fname, "created", str(target)))
    return steps


def init_claude_code(dry_run: bool) -> list[Step]:
    claude_dir = Path.home() / ".claude"
    if not claude_dir.is_dir():
        return [Step("claude-code", "skipped", "~/.claude not found — Claude Code not installed")]
    link = claude_dir / "plugins" / "fettle"
    if _is_clone_mode():
        root = _plugin_root()
    else:
        from fettle.bridge import bridge_dir
        root = bridge_dir()
    if link.is_symlink() or link.exists():
        try:
            if link.resolve() == root.resolve():
                return [Step("claude-code", "ok", f"plugin already linked: {link} -> {root}")]
        except OSError:
            pass
        return [Step("claude-code", "action",
                     f"{link} exists but does not point to {root} — resolve manually")]
    if dry_run:
        return [Step("claude-code", "created", f"(dry-run) would symlink {link} -> {root}")]
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(root)
    return [Step("claude-code", "created", f"symlinked {link} -> {root}")]


def init_opencode(dry_run: bool) -> list[Step]:
    config_dir = Path.home() / ".config" / "opencode"
    if not config_dir.is_dir():
        return [Step("opencode", "skipped", "~/.config/opencode not found — OpenCode not installed")]
    if _is_clone_mode():
        plugin_path = _plugin_root() / "integrations" / "opencode" / "fettle.ts"
    else:
        from fettle.bridge import bridge_dir
        plugin_path = bridge_dir() / "opencode" / "fettle.ts"
    plugin_uri = plugin_path.resolve().as_uri()
    config_path = config_dir / "config.json"
    try:
        config = json.loads(config_path.read_text()) if config_path.is_file() else {}
        if not isinstance(config, dict):
            raise ValueError("config.json is not an object")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [Step("opencode", "action",
                     f"could not parse {config_path} ({exc}) — add plugin entry manually: {plugin_uri}")]

    plugins = config.get("plugin")
    if not isinstance(plugins, list):
        plugins = []
    if plugin_uri in plugins:
        return [Step("opencode", "ok", "plugin already registered")]
    if dry_run:
        return [Step("opencode", "created", f"(dry-run) would register {plugin_uri}")]
    plugins.append(plugin_uri)
    config["plugin"] = plugins
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    return [Step("opencode", "created", f"registered plugin in {config_path} — restart OpenCode")]


def _dispatcher_command() -> str:
    """The hook command every host runs — identical across agents."""
    if _is_clone_mode():
        return f"bash {shlex.quote(str(_plugin_root() / 'fettle' / 'run.sh'))} dispatcher.py"
    from fettle.bridge import dispatcher_command
    return dispatcher_command()


def _merge_hook_events(existing: dict, events: dict[str, dict]) -> bool:
    """Merge fettle hook entries into a Claude-style ``hooks`` mapping.

    ``events`` maps event name -> matcher-group entry. Idempotent: an event
    whose groups already invoke the fettle dispatcher is left untouched.
    Returns True when anything changed.
    """
    command = _dispatcher_command()
    changed = False
    for event, entry in events.items():
        groups = existing.get(event)
        if not isinstance(groups, list):
            groups = []
        already = any(
            isinstance(g, dict) and any(
                isinstance(h, dict) and command == h.get("command")
                for h in (g.get("hooks") or [])
            )
            for g in groups
        )
        if already:
            continue
        groups.append(entry)
        existing[event] = groups
        changed = True
    return changed


def init_codex(dry_run: bool) -> list[Step]:
    """Register the dispatcher in ~/.codex/hooks.json (Stage 13).

    Codex's hook wire is Claude-compatible; hooks.json uses the same
    event/matcher schema as the inline [hooks] table in config.toml.
    JSON is used because the stdlib cannot write TOML. Hooks only fire
    when `features.hooks = true` in config.toml — reported as an action.
    """
    codex_dir = Path.home() / ".codex"
    if not codex_dir.is_dir():
        return [Step("codex", "skipped", "~/.codex not found — Codex CLI not installed")]
    command = _dispatcher_command()
    hooks_path = codex_dir / "hooks.json"
    try:
        config = json.loads(hooks_path.read_text()) if hooks_path.is_file() else {}
        if not isinstance(config, dict):
            raise ValueError("hooks.json is not an object")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [Step("codex", "action",
                     f"could not parse {hooks_path} ({exc}) — add fettle hooks manually")]

    hooks = config.get("hooks")
    if not isinstance(hooks, dict):
        hooks = {}
    events = {
        "PreToolUse": {"matcher": "Write|Edit|Bash",
                       "hooks": [{"type": "command", "command": command, "timeout": 10}]},
        "PostToolUse": {"matcher": "Write|Edit|Bash|Read",
                        "hooks": [{"type": "command", "command": command, "timeout": 15}]},
        "Stop": {"hooks": [{"type": "command", "command": command, "timeout": 60}]},
    }
    action = Step("codex-enable", "action",
                  "ensure `[features] hooks = true` in ~/.codex/config.toml — hooks are off by default")
    if not _merge_hook_events(hooks, events):
        return [Step("codex", "ok", f"hooks already registered in {hooks_path}"), action]
    if dry_run:
        return [Step("codex", "created", f"(dry-run) would register hooks in {hooks_path}"), action]
    config["hooks"] = hooks
    hooks_path.write_text(json.dumps(config, indent=2) + "\n")
    return [Step("codex", "created", f"registered hooks in {hooks_path}"), action]


def init_gemini(dry_run: bool) -> list[Step]:
    """Register the dispatcher in ~/.gemini/settings.json (Stage 13).

    Gemini events: BeforeTool/AfterTool/AfterAgent; matchers use Gemini's
    tool vocabulary; timeouts are in MILLISECONDS (unlike Claude/Codex).
    """
    gemini_dir = Path.home() / ".gemini"
    if not gemini_dir.is_dir():
        return [Step("gemini", "skipped", "~/.gemini not found — Gemini CLI not installed")]
    command = _dispatcher_command()
    settings_path = gemini_dir / "settings.json"
    try:
        config = json.loads(settings_path.read_text()) if settings_path.is_file() else {}
        if not isinstance(config, dict):
            raise ValueError("settings.json is not an object")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [Step("gemini", "action",
                     f"could not parse {settings_path} ({exc}) — add fettle hooks manually")]

    hooks = config.get("hooks")
    if not isinstance(hooks, dict):
        hooks = {}

    def _entry(timeout_ms: int) -> dict:
        return {"name": "fettle", "type": "command", "command": command, "timeout": timeout_ms}

    events = {
        "BeforeTool": {"matcher": "run_shell_command|write_file|replace",
                       "hooks": [_entry(10000)]},
        "AfterTool": {"matcher": "run_shell_command|write_file|replace|read_file",
                      "hooks": [_entry(15000)]},
        "AfterAgent": {"hooks": [_entry(60000)]},
    }
    if not _merge_hook_events(hooks, events):
        return [Step("gemini", "ok", f"hooks already registered in {settings_path}")]
    if dry_run:
        return [Step("gemini", "created", f"(dry-run) would register hooks in {settings_path}")]
    config["hooks"] = hooks
    settings_path.write_text(json.dumps(config, indent=2) + "\n")
    return [Step("gemini", "created", f"registered hooks in {settings_path}")]


def init_pre_commit(repo_root: Path, dry_run: bool) -> list[Step]:
    steps = []
    config_path = repo_root / ".pre-commit-config.yaml"
    if config_path.exists():
        steps.append(Step("pre-commit-config", "ok", "already present"))
    elif dry_run:
        steps.append(Step("pre-commit-config", "created", "(dry-run) would create"))
    else:
        config_path.write_text(PRE_COMMIT_CONFIG)
        steps.append(Step("pre-commit-config", "created", str(config_path)))

    hook_installed = _pre_commit_hook_installed(repo_root)
    if hook_installed:
        steps.append(Step("pre-commit-install", "ok", "commit-time guards wired"))
        return steps

    binary = shutil.which("pre-commit")
    if not binary:
        local = os.path.expanduser("~/.local/bin/pre-commit")
        binary = local if os.path.isfile(local) and os.access(local, os.X_OK) else None
    if not binary:
        steps.append(Step("pre-commit-install", "action",
                          "pre-commit not installed — run: fettle init --install-tools"))
        return steps
    if dry_run:
        steps.append(Step("pre-commit-install", "created", "(dry-run) would run pre-commit install"))
        return steps
    try:
        result = subprocess.run(
            [binary, "install"], cwd=str(repo_root),
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            steps.append(Step("pre-commit-install", "created", "commit-time guards wired"))
        else:
            steps.append(Step("pre-commit-install", "error",
                              (result.stderr or result.stdout).strip()[:200]))
    except (OSError, subprocess.TimeoutExpired) as exc:
        steps.append(Step("pre-commit-install", "error", str(exc)))
    return steps


def _pre_commit_hook_installed(repo_root: Path) -> bool:
    hook = repo_root / ".git" / "hooks" / "pre-commit"
    try:
        return hook.is_file() and "pre-commit" in hook.read_text()
    except OSError:
        return False


def install_tools(dry_run: bool) -> list[Step]:
    """Pinned tool installs via uv — explicit user action, never hook-time (D6)."""
    uv = shutil.which("uv")
    if not uv:
        return [Step("install-tools", "action",
                     "uv not found — install it first: https://docs.astral.sh/uv/")] \
            + install_system_tools(dry_run)
    steps = []
    for tool, version in PINNED_TOOLS.items():
        existing = shutil.which(tool) or (
            os.path.expanduser(f"~/.local/bin/{tool}")
            if os.path.isfile(os.path.expanduser(f"~/.local/bin/{tool}")) else None
        )
        if existing:
            steps.append(Step(f"tool:{tool}", "ok", existing))
            continue
        if dry_run:
            steps.append(Step(f"tool:{tool}", "created", f"(dry-run) would install {tool}=={version}"))
            continue
        result = subprocess.run(
            [uv, "tool", "install", f"{tool}=={version}"],
            capture_output=True, text=True, timeout=600,
        )
        if result.returncode == 0:
            steps.append(Step(f"tool:{tool}", "created", f"{tool}=={version}"))
        else:
            steps.append(Step(f"tool:{tool}", "error", (result.stderr or "").strip()[:200]))
    steps += install_system_tools(dry_run)
    return steps


def install_system_tools(dry_run: bool) -> list[Step]:
    """SYSTEM_TOOLS tier (WP-16): best-effort brew/apt install of gate tools
    that are not pip-installable. No package manager = actionable step with
    the exact command, never a hard error."""
    steps = []
    for tool in SYSTEM_TOOLS:
        existing = shutil.which(tool)
        if existing:
            steps.append(Step(f"tool:{tool}", "ok", existing))
            continue
        argv = system_install_argv(tool)
        if argv is None:
            steps.append(Step(f"tool:{tool}", "action", system_install_hint(tool)))
            continue
        display = " ".join(a for a in argv if a != "-n")
        if dry_run:
            steps.append(Step(f"tool:{tool}", "created", f"(dry-run) would run: {display}"))
            continue
        result = subprocess.run(argv, capture_output=True, text=True, timeout=600)
        if result.returncode == 0 and shutil.which(tool):
            steps.append(Step(f"tool:{tool}", "created", f"installed via {display}"))
        else:
            detail = (result.stderr or result.stdout or "").strip()[:160]
            steps.append(Step(f"tool:{tool}", "action",
                              f"install failed — run manually: {display}"
                              + (f" ({detail})" if detail else "")))
    return steps


def run_init(repo_root: Path, *, tools: bool = False, dry_run: bool = False) -> tuple[list[Step], int]:
    steps: list[Step] = []
    steps += init_repo_files(repo_root, dry_run)
    if not _is_clone_mode():
        from fettle.bridge import publish_bridge
        bridge = publish_bridge(dry_run=dry_run)
        steps.append(Step("bridge", bridge.status, bridge.detail))
        if bridge.status == "error":
            return steps, 1
    steps += init_claude_code(dry_run)
    steps += init_opencode(dry_run)
    steps += init_codex(dry_run)
    steps += init_gemini(dry_run)
    steps += init_pre_commit(repo_root, dry_run)
    # WP-18: guided workflows in each detected host's slash-command format.
    from fettle.workflows import install_for_init
    steps += install_for_init(repo_root, dry_run)
    if tools:
        steps += install_tools(dry_run)
    exit_code = 1 if any(s.status == "error" for s in steps) else 0
    return steps, exit_code


_MARKS = {"ok": "ok ", "created": "new", "skipped": "-- ", "action": "!! ", "error": "ERR"}


def print_steps(steps: list[Step]) -> None:
    print("── fettle init ──\n")
    for s in steps:
        print(f"[{_MARKS.get(s.status, '?')}] {s.name:<20} {s.detail}")
    actions = [s for s in steps if s.status == "action"]
    if actions:
        print(f"\n{len(actions)} step(s) need your attention (marked !!).")
    else:
        print("\n✓ Fettle is wired. `fettle doctor` verifies the environment.")
