"""WP-18 — Cross-environment workflow distribution (v1.7.0, directive D3).

The 17 guided workflows in commands/*.md are the canonical source (Claude
Code plugin format). This module renders them into each supported host's
native slash-command format and installs them idempotently:

  VS Code   .github/prompts/fettle-<name>.prompt.md      /fettle-<name>
  Codex     ~/.codex/prompts/fettle-<name>.md            /prompts:fettle-<name>
  Gemini    .gemini/commands/fettle/<name>.toml          /fettle:<name>
  OpenCode  .opencode/commands/fettle-<name>.md          /fettle-<name>
  Claude    .claude/commands/fettle/<name>.md            /fettle:<name>
            (only when the plugin symlink is absent — the plugin already
            provides these)

Ownership: every rendered file carries a generation marker. Files without
the marker are user-owned and never overwritten (same merge discipline as
init_codex/init_gemini). Format facts verified against official host docs
2026-08-03 — see docs/engagement/16-v17-workflows-distribution.md.
"""

from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root (clone mode)
from fettle._resources import commands_dir  # noqa: E402
from fettle.init_cmd import Step  # noqa: E402

AGENTS = ("claude", "vscode", "codex", "gemini", "opencode")

MD_MARKER = "<!-- generated by fettle workflows install -->"
TOML_MARKER = "# generated by fettle workflows install"

_ARGS_NOTE = "$ARGUMENTS refers to any text the user typed after the slash command."


@dataclass
class Workflow:
    name: str
    description: str
    argument_hint: str
    user_invocable: bool
    body: str


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_command(path: Path) -> Workflow:
    """Parse a canonical commands/*.md file.

    Frontmatter is at most five flat string keys. This small parser keeps
    workflow installation independent from the general YAML parser.
    """
    text = path.read_text(encoding="utf-8")
    meta: dict[str, str] = {}
    body = text
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for i, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                body = "\n".join(lines[i + 1:]).lstrip("\n")
                break
            if ":" in line:
                key, _, value = line.partition(":")
                meta[key.strip()] = _unquote(value)
    description = meta.get("description", "")
    if not description:
        # No frontmatter — first prose line (skip headings/blank).
        for line in body.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                description = stripped
                break
    return Workflow(
        name=meta.get("name", path.stem),
        description=description,
        argument_hint=meta.get("argument-hint", ""),
        user_invocable=meta.get("user-invocable", "true").lower() != "false",
        body=body,
    )


def load_workflows(source: Path | None = None) -> list[Workflow]:
    source = source or commands_dir()
    flows = [parse_command(p) for p in sorted(source.glob("*.md"))]
    return [w for w in flows if w.user_invocable]


# ── Renderers — pure (Workflow) -> str ──────────────────────────────────

def _yaml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _md_with_frontmatter(keys: list[tuple[str, str]], body: str) -> str:
    front = "\n".join(f"{k}: {_yaml_str(v)}" for k, v in keys if v)
    preamble = f"{_ARGS_NOTE}\n\n" if "$ARGUMENTS" in body else ""
    return f"---\n{front}\n---\n{MD_MARKER}\n\n{preamble}{body.rstrip()}\n"


def render_claude(w: Workflow) -> str:
    """Standalone Claude command — canonical format, marker added."""
    return _md_with_frontmatter(
        [("name", w.name), ("description", w.description),
         ("argument-hint", w.argument_hint)],
        w.body,
    )


def render_vscode(w: Workflow) -> str:
    """VS Code prompt file. No `tools` key — Claude tool names don't map to
    VS Code tool names; the agent's defaults apply. VS Code has no argument
    placeholder: user text after /fettle-<name> is appended to the prompt,
    so the $ARGUMENTS preamble bridges the contract."""
    return _md_with_frontmatter(
        [("name", f"fettle-{w.name}"), ("description", w.description),
         ("argument-hint", w.argument_hint)],
        w.body,
    )


def render_codex(w: Workflow) -> str:
    """Codex custom prompt (~/.codex/prompts, top-level only, $ARGUMENTS
    supported natively). Deprecated upstream in favor of skills but still
    functional — see design doc."""
    return _md_with_frontmatter(
        [("description", w.description), ("argument-hint", w.argument_hint)],
        w.body,
    )


def render_opencode(w: Workflow) -> str:
    """OpenCode command markdown ($ARGUMENTS supported natively)."""
    return _md_with_frontmatter([("description", w.description)], w.body)


def render_gemini(w: Workflow) -> str:
    """Gemini CLI TOML command. Stdlib cannot write TOML, so escape by hand:
    in a multi-line basic string, `\\` and `\"` escapes cover everything the
    markdown bodies can contain. Gemini's argument placeholder is {{args}}."""
    body = w.body.replace("$ARGUMENTS", "{{args}}")
    escaped = body.replace("\\", "\\\\").replace('"', '\\"')
    description = w.description.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"{TOML_MARKER}\n"
        f'description = "{description}"\n'
        f'prompt = """\n{escaped.rstrip()}\n"""\n'
    )


_RENDERERS = {
    "claude": render_claude,
    "vscode": render_vscode,
    "codex": render_codex,
    "gemini": render_gemini,
    "opencode": render_opencode,
}

_MARKERS = {agent: TOML_MARKER if agent == "gemini" else MD_MARKER
            for agent in AGENTS}


# ── Install ─────────────────────────────────────────────────────────────

def _detected(agent: str, repo_root: Path) -> bool:
    home = Path.home()
    if agent == "claude":
        return (home / ".claude").is_dir()
    if agent == "codex":
        return (home / ".codex").is_dir()
    if agent == "gemini":
        return (home / ".gemini").is_dir()
    if agent == "opencode":
        return (home / ".config" / "opencode").is_dir()
    if agent == "vscode":
        return ((repo_root / ".vscode").is_dir() or (repo_root / ".github").is_dir()
                or shutil.which("code") is not None)
    return False


def target_path(agent: str, scope: str, name: str, repo_root: Path) -> Path | None:
    """Where a rendered workflow lands. None = unsupported combination."""
    home = Path.home()
    if agent == "claude":
        base = (repo_root / ".claude" if scope == "project" else home / ".claude")
        return base / "commands" / "fettle" / f"{name}.md"
    if agent == "vscode":
        if scope == "user":
            return None  # profile storage is VS Code-managed; no stable path
        return repo_root / ".github" / "prompts" / f"fettle-{name}.prompt.md"
    if agent == "codex":
        if scope == "project":
            return None  # Codex scans only top-level ~/.codex/prompts/
        return home / ".codex" / "prompts" / f"fettle-{name}.md"
    if agent == "gemini":
        base = (repo_root / ".gemini" if scope == "project" else home / ".gemini")
        return base / "commands" / "fettle" / f"{name}.toml"
    if agent == "opencode":
        if scope == "project":
            return repo_root / ".opencode" / "commands" / f"fettle-{name}.md"
        return home / ".config" / "opencode" / "commands" / f"fettle-{name}.md"
    return None


_UNSUPPORTED = {
    ("codex", "project"): "Codex reads only ~/.codex/prompts — use --user",
    ("vscode", "user"): "VS Code user prompts live in profile storage — "
                        "use --project, or Chat: New Prompt File in VS Code",
}


def _write(target: Path, content: str, marker: str, dry_run: bool) -> str:
    """Returns: created | updated | ok | user-owned."""
    if target.is_file():
        existing = target.read_text(encoding="utf-8")
        if existing == content:
            return "ok"
        if marker not in existing:
            return "user-owned"
        if not dry_run:
            target.write_text(content, encoding="utf-8")
        return "updated"
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return "created"


def install(agents: list[str], scope: str, repo_root: Path,
            dry_run: bool = False, *, detect: bool = False) -> list[Step]:
    """Render + install workflows. One summary Step per agent; individual
    action Steps for user-owned conflicts (never clobbered).

    detect=True (used by --agent all and fettle init) silently skips hosts
    that are not installed; an explicitly named agent always installs.
    """
    steps: list[Step] = []
    source = commands_dir()
    if not source.is_dir():
        hint = "pipx install . --force" if "site-packages" in str(source) else "git clone and run from repo root"
        return [Step("workflows", "error", f"commands directory not found: {source} ({hint})")]
    flows = load_workflows(source)
    if not flows:
        return [Step("workflows", "error", f"no .md workflow files in {source}")]
    for agent in agents:
        if detect and not _detected(agent, repo_root):
            steps.append(Step(f"workflows:{agent}", "skipped", f"{agent} not detected"))
            continue
        if agent == "claude" and scope == "project" and \
                (Path.home() / ".claude" / "plugins" / "fettle").exists():
            steps.append(Step("workflows:claude", "ok",
                              "plugin symlink provides /fettle:* commands"))
            continue
        reason = _UNSUPPORTED.get((agent, scope))
        if reason:
            steps.append(Step(f"workflows:{agent}", "action", reason))
            continue
        render = _RENDERERS[agent]
        marker = _MARKERS[agent]
        counts = {"created": 0, "updated": 0, "ok": 0}
        conflicts: list[str] = []
        target_dir = ""
        for w in flows:
            target = target_path(agent, scope, w.name, repo_root)
            assert target is not None  # unsupported combos handled above
            target_dir = str(target.parent)
            result = _write(target, render(w), marker, dry_run)
            if result == "user-owned":
                conflicts.append(str(target))
            else:
                counts[result] += 1
        written = counts["created"] + counts["updated"]
        prefix = "(dry-run) would write" if dry_run and written else "installed"
        detail = (f"{prefix} {written}, {counts['ok']} current → {target_dir}"
                  if written else f"{counts['ok']} current in {target_dir}")
        steps.append(Step(f"workflows:{agent}", "created" if written else "ok", detail))
        for path in conflicts:
            steps.append(Step(f"workflows:{agent}", "action",
                              f"{path} exists without the fettle marker — not overwritten"))
    return steps


def install_for_init(repo_root: Path, dry_run: bool) -> list[Step]:
    """fettle init wiring: project scope everywhere it exists; Codex only
    has user scope. Detection-gated — undetected hosts are skipped."""
    steps = install(["claude", "vscode", "gemini", "opencode"], "project",
                    repo_root, dry_run, detect=True)
    steps += install(["codex"], "user", repo_root, dry_run, detect=True)
    return steps


# ── Doctor probe ────────────────────────────────────────────────────────

def check_workflows(repo_root: Path | None = None) -> list[dict]:
    """Warn-only doctor probe: rendered workflows present and current for
    each detected host. User-owned files (marker stripped) count as current
    — the user took ownership deliberately."""
    repo_root = repo_root or Path.cwd()
    checks: list[dict] = []
    try:
        flows = load_workflows()
    except OSError:
        return checks
    if not flows:
        return checks
    for agent in AGENTS:
        if not _detected(agent, repo_root):
            continue
        scope = "user" if agent == "codex" else "project"
        if agent == "claude" and (Path.home() / ".claude" / "plugins" / "fettle").exists():
            checks.append({"name": f"workflows-{agent}", "required": False, "ok": True,
                           "detail": "plugin symlink provides /fettle:* commands"})
            continue
        render = _RENDERERS[agent]
        marker = _MARKERS[agent]
        stale = 0
        for w in flows:
            target = target_path(agent, scope, w.name, repo_root)
            if target is None:
                continue
            if not target.is_file():
                stale += 1
                continue
            existing = target.read_text(encoding="utf-8")
            if existing != render(w) and marker in existing:
                stale += 1
        ok = stale == 0
        flag = "" if scope == "project" else f" --agent {agent} --user"
        detail = (f"{len(flows)} workflows current"
                  if ok else f"{stale}/{len(flows)} missing or stale — "
                             f"fix: fettle workflows install{flag}")
        checks.append({"name": f"workflows-{agent}", "required": False,
                       "ok": ok, "detail": detail})
    return checks


INVOCATIONS = {
    "claude": "/fettle:{name}",
    "vscode": "/fettle-{name}",
    "codex": "/prompts:fettle-{name}",
    "gemini": "/fettle:{name}",
    "opencode": "/fettle-{name}",
}


def list_rows() -> list[dict]:
    """`fettle workflows list` payload: canonical names + per-host invocation."""
    return [
        {"name": w.name, "description": w.description,
         "invocations": {agent: pattern.format(name=w.name)
                         for agent, pattern in INVOCATIONS.items()}}
        for w in load_workflows()
    ]
