"""Tests for `fettle init --interactive` / `--profile` (v1.6 slice B)."""

import tomllib

import pytest

from fettle.config_schema import validate_config
from fettle.init_interview import (
    PROFILES,
    detect_stack,
    render_config,
    run_interview,
    write_config,
)


# ─── generated config validates (D-B2) ───────────────────────────────────────


@pytest.mark.parametrize("profile", sorted(PROFILES))
def test_profile_config_parses_and_validates(profile):
    content = render_config(dict(PROFILES[profile]), {"languages": ["python"], "ci": "github"})
    parsed = tomllib.loads(content)
    errors, _warnings = validate_config(parsed)
    assert errors == [], f"{profile}: {errors}"


def test_solo_is_advisory_team_enables_plans_enterprise_enforces():
    solo = tomllib.loads(render_config(dict(PROFILES["solo"]), {"languages": [], "ci": ""}))
    team = tomllib.loads(render_config(dict(PROFILES["team"]), {"languages": [], "ci": ""}))
    ent = tomllib.loads(render_config(dict(PROFILES["enterprise"]), {"languages": [], "ci": ""}))

    assert solo["gates"]["lint"]["mode"] == "advisory"
    assert solo["gates"]["plan"]["enabled"] is False
    assert "agent_spawn" not in solo["gates"]

    assert team["gates"]["plan"]["enabled"] is True
    assert team["gates"]["worklog"]["scope"] == "session"

    assert ent["gates"]["lint"]["mode"] == "enforce"
    assert ent["gates"]["bash_audit"]["enabled"] is True
    assert ent["gates"]["agent_spawn"]["mode"] == "enforce"
    assert ent["worktrees"]["require"] is True


def test_render_notes_unconfirmed_stack():
    answers = dict(PROFILES["solo"])
    answers["stack_confirmed"] = False
    content = render_config(answers, {"languages": ["go"], "ci": ""})
    assert "flagged the detected stack as wrong" in content


# ─── detection ───────────────────────────────────────────────────────────────


def test_detect_stack(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    (tmp_path / "go.mod").write_text("module x\n")
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    d = detect_stack(tmp_path)
    assert "python" in d["languages"] and "go" in d["languages"]
    assert d["ci"] == "github"
    assert detect_stack(tmp_path / "nowhere") == {"languages": [], "ci": ""}


# ─── interview ───────────────────────────────────────────────────────────────


def test_run_interview_scripted(tmp_path):
    answers_in = iter(["y", "", "n", "y", ""])  # team=y, strict=default(n), ...
    said = []
    answers = run_interview(tmp_path, ask=lambda _p: next(answers_in),
                            say=said.append)
    assert answers["team"] is True
    assert answers["strict"] is False
    assert answers["compliance"] is False
    assert answers["multi_agent"] is True
    assert answers["stack_confirmed"] is True  # default Y
    assert said  # intro printed


# ─── write_config (D-B1) ─────────────────────────────────────────────────────


def test_write_config_refuses_existing_without_force(tmp_path):
    (tmp_path / ".fettle.toml").write_text("# existing\n")
    ok, msg = write_config(tmp_path, "# new\n")
    assert not ok and "already exists" in msg
    assert (tmp_path / ".fettle.toml").read_text() == "# existing\n"
    ok, _ = write_config(tmp_path, "# new\n", force=True)
    assert ok
    assert (tmp_path / ".fettle.toml").read_text() == "# new\n"


# ─── CLI ─────────────────────────────────────────────────────────────────────


def _init_ns(**over):
    import argparse
    ns = argparse.Namespace(install_tools=False, dry_run=True, json=False,
                            interactive=False, profile=None, force=False)
    for k, v in over.items():
        setattr(ns, k, v)
    return ns


def test_cli_init_profile_writes_annotated_config(tmp_path, monkeypatch, capsys):
    from fettle import cli, paths
    monkeypatch.setattr(paths, "find_repo_root", lambda *a, **k: tmp_path)
    with pytest.raises(SystemExit) as e:
        cli.cmd_init(_init_ns(profile="team"))
    assert e.value.code == 0
    content = (tmp_path / ".fettle.toml").read_text()
    assert "generated by `fettle init`" in content
    assert "✓ wrote" in capsys.readouterr().out


def test_cli_init_profile_refuses_existing(tmp_path, monkeypatch, capsys):
    from fettle import cli, paths
    monkeypatch.setattr(paths, "find_repo_root", lambda *a, **k: str(tmp_path))
    (tmp_path / ".fettle.toml").write_text("# keep me\n")
    with pytest.raises(SystemExit) as e:
        cli.cmd_init(_init_ns(profile="solo"))
    assert e.value.code == 2
    assert (tmp_path / ".fettle.toml").read_text() == "# keep me\n"


def test_cli_init_interactive_needs_tty(tmp_path, monkeypatch, capsys):
    from fettle import cli, paths
    monkeypatch.setattr(paths, "find_repo_root", lambda *a, **k: str(tmp_path))
    monkeypatch.setattr("sys.stdin.isatty", lambda: False)
    with pytest.raises(SystemExit) as e:
        cli.cmd_init(_init_ns(interactive=True))
    assert e.value.code == 2
    assert "--profile" in capsys.readouterr().err
