"""`fettle ci` — one enforced gate sequence, and the workflow that runs it.

`run_ci` composes the gates Fettle owns — boundary scan, quality gate
(new-vs-baseline), plan validation — into a single pass/fail. It fails
CLOSED: a gate that errors is a failure, never a silent skip. `generate_
workflow` emits a `.github/workflows/fettle.yml` that runs `fettle ci`, so
an adopting repo inherits the same gates (crucially the boundary scan) from
its first commit rather than hand-rolling a CI that forgets one.
"""

from __future__ import annotations

import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from boundary_scan import scan_repo  # noqa: E402
from config import load_config  # noqa: E402

logger = logging.getLogger("fettle.ci")


def _gate_boundary(root: str, cfg: dict) -> dict:
    try:
        findings = scan_repo(root, cfg)
    except Exception as e:  # noqa: BLE001 — fail closed, surface the error
        logger.error("boundary gate crashed: %s", e, exc_info=True)
        return {"name": "boundary", "ok": False, "error": str(e) or repr(e), "findings": []}
    return {
        "name": "boundary",
        "ok": not findings,
        "findings": [f"{f.path}:{f.line} [{f.code}] {f.message}" for f in findings],
    }


def _gate_quality(root: str, cfg: dict) -> dict:
    """Ruff+semgrep, reported new-vs-committed-baseline (errors fail)."""
    try:
        from pathlib import Path

        from baseline import filter_new_violations, load_baseline
        from quality_scan import load_config as _lc
        from quality_scan import run_ruff, run_semgrep

        _cfg = _lc(root)  # sets severity globals inside quality_scan
        findings = run_ruff(root) + run_semgrep(root)
        baseline = load_baseline(Path(root))
        if baseline:
            findings = filter_new_violations(findings, baseline)
        errors = [f for f in findings if f.get("severity") == "error"]
    except Exception as e:  # noqa: BLE001 — fail closed
        logger.error("quality gate crashed: %s", e, exc_info=True)
        return {"name": "quality", "ok": False, "error": str(e) or repr(e), "findings": []}
    return {
        "name": "quality",
        "ok": not errors,
        "findings": [f"{f.get('file')}:{f.get('line')} {f.get('code')}" for f in errors],
    }


def _gate_plans(root: str, cfg: dict) -> dict:
    """Validate any plan docs present; a repo with no plans passes."""
    try:
        import glob

        from plan_validator import validate_plan

        gate = cfg.get("gates", {}).get("plan", {})
        plan_dir = gate.get("plan_dir", "docs")
        plan_glob = gate.get("plan_glob", "*plan*.md")
        plans = glob.glob(os.path.join(root, plan_dir, plan_glob))
        failed = []
        for plan in plans:
            with open(plan, encoding="utf-8", errors="ignore") as fh:
                result = validate_plan(fh.read())
            if not result.passed:
                failed.append(os.path.relpath(plan, root))
    except Exception as e:  # noqa: BLE001 — fail closed
        logger.error("plan gate crashed: %s", e, exc_info=True)
        return {"name": "plans", "ok": False, "error": str(e) or repr(e), "findings": []}
    return {"name": "plans", "ok": not failed, "findings": failed}


def run_ci(root: str) -> dict:
    """Run the enforced gate sequence. Returns {ok, gates:[...]}."""
    root = os.path.abspath(root)
    cfg = load_config(root)
    gates = [_gate_boundary(root, cfg), _gate_quality(root, cfg), _gate_plans(root, cfg)]
    return {"ok": all(g["ok"] for g in gates), "gates": gates}


WORKFLOW_TEMPLATE = """\
name: Fettle CI

on:
  push:
    branches: [main]
  pull_request:

# Generated by `fettle ci init`. Runs Fettle's enforced gates — the boundary
# scan (secrets, out-of-project paths, forbidden strings), the quality gate
# vs the committed baseline, and plan validation — on every push and PR.
jobs:
  fettle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Fettle tools
        run: python -m pip install --quiet ruff==0.15.20 semgrep==1.168.0
      - name: Fettle boundary + quality + plan gates
        run: python "$FETTLE_HOME/scripts/cli.py" ci --root .
      - name: Tests
        run: |
          if [ -d tests ]; then python -m pip install --quiet pytest && python -m pytest -q; fi
"""


def generate_workflow() -> str:
    return WORKFLOW_TEMPLATE


_CONFIG_SEED = """\
# Fettle configuration. See docs/CONFIG.md.

[boundary]
# Sibling projects / strings this package must NOT reference, so it stays
# generic and standalone. The secret and out-of-project-path checks are
# always on; add names here to also forbid cross-package references.
forbidden = []

[gates.ci_bootstrap]
# CI is now set up for this repo — hard-enforce it: block edits if the
# workflow is ever removed. Set mode = "advisory" to only warn.
enabled = true
mode = "strict"
"""


def init_ci(root: str, dry_run: bool = False) -> str:
    """Write the workflow and seed .fettle.toml's [boundary] section."""
    root = os.path.abspath(root)
    workflow_path = os.path.join(root, ".github", "workflows", "fettle.yml")
    workflow = generate_workflow()
    summary = f"# {workflow_path}\n{workflow}\n# .fettle.toml [boundary] seed\n{_CONFIG_SEED}"
    if dry_run:
        return summary
    os.makedirs(os.path.dirname(workflow_path), exist_ok=True)
    with open(workflow_path, "w") as f:
        f.write(workflow)
    toml_path = os.path.join(root, ".fettle.toml")
    if not os.path.isfile(toml_path):
        with open(toml_path, "w") as f:
            f.write(_CONFIG_SEED)
    else:
        with open(toml_path) as f:
            existing = f.read()
        if "[boundary]" not in existing:
            with open(toml_path, "a") as f:
                f.write("\n" + _CONFIG_SEED)
    return summary


def _print_result(result: dict) -> int:
    for g in result["gates"]:
        mark = "✓" if g["ok"] else "✗"
        print(f"  {mark} {g['name']}")
        if g.get("error"):
            print(f"      error: {g['error']}", file=sys.stderr)
        for finding in g.get("findings", [])[:20]:
            print(f"      {finding}", file=sys.stderr)
    print("Fettle CI: " + ("PASS" if result["ok"] else "FAIL"))
    return 0 if result["ok"] else 1


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Fettle CI — enforced gates")
    parser.add_argument("--root", default=".")
    sub = parser.add_subparsers(dest="action")
    p_init = sub.add_parser("init", help="Write .github/workflows/fettle.yml")
    p_init.add_argument("--dry-run", action="store_true")
    p_init.add_argument("--root", default=".")
    args = parser.parse_args(argv)

    if args.action == "init":
        out = init_ci(args.root, dry_run=args.dry_run)
        if args.dry_run:
            print(out)
        else:
            print("Wrote .github/workflows/fettle.yml and seeded .fettle.toml [boundary].")
        return 0
    return _print_result(run_ci(args.root))


if __name__ == "__main__":
    sys.exit(main())
